version: '3.8'

services:
  research-agent:
    build: .
    container_name: research-agent
    ports:
      - "8501:8501"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
      - SERPAPI_KEY=${SERPAPI_KEY}
      - MAX_RESULTS=${MAX_RESULTS:-10}
      - MAX_TOKENS=${MAX_TOKENS:-4000}
      - TEMPERATURE=${TEMPERATURE:-0.3}
      - VECTOR_DB_PATH=/app/data/chroma_db
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      - CACHE_DIR=/app/cache
      - CACHE_EXPIRY_HOURS=${CACHE_EXPIRY_HOURS:-24}
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3
    networks:
      - research-network

networks:
  research-network:
    driver: bridge

volumes:
  research-data:
  research-cache:
  research-logs:
